# Site settings
title: Mocree
email: contact@mocree.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/landing"
url: "http://www.mocree.com"

# Social
instagram_username: mocreemusic
twitter_username: mocreemusic
github_username: mocree

# Build settings
markdown: kramdown
